Repository FuelLabs/fuel-vm, pull requests merged in 2022-10, with the labels that each got.

#234 Add gas initial costs
  Cargo.toml
  src/gas.rs
  src/interpreter/debug.rs
  src/interpreter/executors/instruction.rs
  src/interpreter/executors/instruction/tests.rs
  src/interpreter/executors/instruction/tests/reserved_registers.rs
  src/interpreter/flow.rs
  src/interpreter/gas.rs
  src/interpreter/gas/consts.rs
  src/interpreter/memory.rs
  src/util.rs
  tests/blockchain.rs
  tests/bug-id.rs
  tests/cgas.rs
  tests/code_coverage.rs
  tests/profile_gas.rs
Labels: enhancement

#240 Avoid rounding issues in MLOG instruction
  src/interpreter/executors/instruction.rs
  src/interpreter/executors/instruction/tests.rs
  src/interpreter/executors/instruction/tests/math_operations.rs
Labels: bug

#235 Refactoring of getters/setters/offset and adapt `Interpreter` to work with generic transactions.
  Cargo.toml
  fuzz/fuzz_targets/grammar_aware.rs
  src/backtrace.rs
  src/context.rs
  src/error.rs
  src/interpreter.rs
  src/interpreter/alu.rs
  src/interpreter/balances.rs
  src/interpreter/blockchain.rs
  src/interpreter/constructors.rs
  src/interpreter/contract.rs
  src/interpreter/crypto.rs
  src/interpreter/debug.rs
  src/interpreter/executors/debug.rs
  src/interpreter/executors/instruction.rs
  src/interpreter/executors/instruction/tests/reserved_registers.rs
  src/interpreter/executors/main.rs
  src/interpreter/executors/predicate.rs
  src/interpreter/flow.rs
  src/interpreter/frame.rs
  src/interpreter/gas.rs
  src/interpreter/initialization.rs
  src/interpreter/internal.rs
  src/interpreter/log.rs
  src/interpreter/memory.rs
  src/interpreter/metadata.rs
  src/interpreter/post_execution.rs
  src/lib.rs
  src/memory_client.rs
  src/predicate.rs
  src/state.rs
  src/transactor.rs
  src/util.rs
  tests/alu.rs
  tests/backtrace.rs
  tests/blockchain.rs
  tests/contract.rs
  tests/encoding.rs
  tests/flow.rs
  tests/gas_factor.rs
  tests/metadata.rs
  tests/outputs.rs
  tests/predicate.rs
Labels: breaking

#244 Define WORD_SIZE only once
  src/call.rs
  src/interpreter/blockchain.rs
  src/interpreter/executors/instruction.rs
  tests/backtrace.rs
  tests/blockchain.rs
  tests/code_coverage.rs
  tests/flow.rs
Labels: tech-debt

#250 Bugfix: Update outputs of `Create` transaction after execution
  src/interpreter.rs
  src/interpreter/executors/main.rs
  src/util.rs
  tests/outputs.rs
Labels: bug
