Repository FuelLabs/fuel-vm, pull requests merged in 2022-11, with the labels that each got.

#259 Add ALU test cases for MLOG instruction
  tests/alu.rs
Labels: tech-debt

#262 Fix MROO rounding issues
  Cargo.toml
  src/interpreter/executors/instruction.rs
  src/interpreter/executors/instruction/tests/math_operations.rs
  tests/alu.rs
Labels: bug

#267 Enable Clippy in CI
  .github/workflows/ci.yml
  src/crypto.rs
  src/error.rs
  src/interpreter/balances.rs
  src/interpreter/executors/main.rs
  src/interpreter/internal.rs
  src/state.rs
  src/util.rs
  tests/alu.rs
  tests/blockchain.rs
  tests/cgas.rs
  tests/contract.rs
  tests/encoding.rs
  tests/flow.rs
  tests/metadata.rs
  tests/predicate.rs
Labels: enhancement

#271 Fix bug in load byte
  Cargo.toml
  src/interpreter/executors/instruction.rs
  src/interpreter/memory.rs
  tests/memory.rs
Labels: bug
