Repository FuelLabs/fuel-vm, pull requests merged in 2023-11, with the labels that each got.

#626 Upgrade to Rust 1.73 and fix related todo
  .github/workflows/ci.yml
  fuel-tx/src/transaction/fee.rs
  fuel-vm/src/interpreter/receipts.rs
Labels: no changelog

#631 Simplify asm in some tests
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/crypto.rs
  fuel-vm/src/tests/memory.rs
Labels: no changelog

#633 Limit ReceiptsCtx to u16::MAX receipts
  CHANGELOG.md
  fuel-asm/src/panic_reason.rs
  fuel-vm/src/error.rs
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/interpreter/contract.rs
  fuel-vm/src/interpreter/diff/tests.rs
  fuel-vm/src/interpreter/executors/instruction.rs
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/interpreter/flow.rs
  fuel-vm/src/interpreter/flow/ret_tests.rs
  fuel-vm/src/interpreter/internal.rs
  fuel-vm/src/interpreter/log.rs
  fuel-vm/src/interpreter/receipts.rs
  fuel-vm/src/tests/mod.rs
  fuel-vm/src/tests/receipts.rs
Labels: breaking, fuel-vm

#625 Split ArithmeticError into more granular errors
  CHANGELOG.md
  fuel-asm/src/panic_reason.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/policies.rs
  fuel-tx/src/transaction/validity/error.rs
  fuel-types/src/numeric_types.rs
  fuel-vm/src/arith.rs
  fuel-vm/src/checked_transaction.rs
  fuel-vm/src/checked_transaction/balances.rs
  fuel-vm/src/convert.rs
  fuel-vm/src/interpreter.rs
  fuel-vm/src/interpreter/balances.rs
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/interpreter/blockchain/other_tests.rs
  fuel-vm/src/interpreter/contract.rs
  fuel-vm/src/interpreter/contract/tests.rs
  fuel-vm/src/interpreter/flow.rs
  fuel-vm/src/interpreter/metadata.rs
  fuel-vm/src/lib.rs
Labels: breaking, tech-debt, fuel-asm

#636 v0.42.0 npm publishing fix
  .npm/packages/fuel-asm/index.test.cjs
  .npm/packages/fuel-asm/index.test.mjs
  .npm/pnpm-lock.yaml
Labels: no changelog
