Repository FuelLabs/fuel-vm, pull requests merged in 2023-09, with the labels that each got.

#580 feat: Impl `fmt::Display` for canonical Error
  fuel-types/src/canonical.rs
Labels: no changelog

#581 fix: Organize `ConsensusParameters` gas costs in alphabetical order
  fuel-tx/src/transaction/consensus_parameters/gas.rs
Labels: no changelog

#578 no_std fuel-crypto
  .github/workflows/ci.yml
  CHANGELOG.md
  fuel-crypto/Cargo.toml
  fuel-crypto/benches/signature.rs
  fuel-crypto/src/ed25519.rs
  fuel-crypto/src/error.rs
  fuel-crypto/src/lib.rs
  fuel-crypto/src/message.rs
  fuel-crypto/src/secp256.rs
  fuel-crypto/src/secp256/backend.rs
  fuel-crypto/src/secp256/backend/k1/k256.rs
  fuel-crypto/src/secp256/backend/k1/secp256k1.rs
  fuel-crypto/src/secp256/backend/r1/p256.rs
  fuel-crypto/src/secp256/public.rs
  fuel-crypto/src/secp256/secret.rs
  fuel-crypto/src/secp256/signature.rs
  fuel-crypto/src/secp256/signature_format.rs
  fuel-crypto/src/secp256k1/public.rs
  fuel-crypto/src/secp256k1/secret.rs
  fuel-crypto/src/secp256k1/signature.rs
  fuel-crypto/src/tests/mnemonic.rs
  fuel-crypto/src/tests/mod.rs
  fuel-crypto/src/tests/signature.rs
  fuel-tx/src/builder.rs
  fuel-tx/src/tests/valid_cases/input.rs
  fuel-tx/test-helpers/src/lib.rs
  fuel-vm/Cargo.toml
  fuel-vm/src/checked_transaction.rs
  fuel-vm/src/interpreter/executors/main/tests.rs
  fuel-vm/src/interpreter/internal/tests.rs
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/code_coverage.rs
  fuel-vm/src/tests/metadata.rs
  fuel-vm/src/tests/predicate.rs
  fuel-vm/src/tests/profile_gas.rs
  fuel-vm/src/tests/validation.rs
  fuel-vm/src/util.rs
Labels: breaking, fuel-crypto

#587 Replace thiserror with derive_more::Display
  CHANGELOG.md
  fuel-merkle/Cargo.toml
  fuel-merkle/src/binary/merkle_tree.rs
  fuel-merkle/src/common/error.rs
  fuel-merkle/src/common/node.rs
  fuel-merkle/src/common/prefix.rs
  fuel-merkle/src/sparse/merkle_tree.rs
  fuel-merkle/src/sparse/node.rs
  fuel-merkle/src/sum/merkle_tree.rs
  fuel-tx/Cargo.toml
  fuel-tx/src/transaction/types/utxo_id.rs
  fuel-tx/src/transaction/validity/error.rs
  fuel-vm/Cargo.toml
  fuel-vm/src/error.rs
Labels: breaking

#591 Fix publishing of the `fuel-asm 0.38`
  fuel-asm/Cargo.toml
Labels: no changelog
