Repository FuelLabs/fuel-vm, pull requests merged in 2024-12, with the labels that each got.

#875 chore: bump wasm-bindgen from `0.2.88` to `0.2.97`
  CHANGELOG.md
  fuel-asm/Cargo.toml
  fuel-tx/Cargo.toml
  fuel-types/Cargo.toml
Labels: fuel-asm, fuel-tx, fuel-types

#868 Add a separate error for nonexistent contract input
  CHANGELOG.md
  fuel-asm/src/panic_reason.rs
  fuel-vm/src/interpreter/executors/main.rs
Labels: breaking

#876 Replace derivative by educe
  fuel-tx/Cargo.toml
  fuel-tx/src/contract.rs
  fuel-tx/src/receipt.rs
  fuel-tx/src/transaction/consensus_parameters.rs
  fuel-tx/src/transaction/types/blob.rs
  fuel-tx/src/transaction/types/chargeable_transaction.rs
  fuel-tx/src/transaction/types/create.rs
  fuel-tx/src/transaction/types/input/coin.rs
  fuel-tx/src/transaction/types/input/message.rs
  fuel-tx/src/transaction/types/input/predicate.rs
  fuel-tx/src/transaction/types/mint.rs
  fuel-tx/src/transaction/types/script.rs
  fuel-tx/src/transaction/types/upgrade.rs
  fuel-tx/src/transaction/types/upload.rs
  fuel-tx/src/transaction/types/witness.rs
  fuel-tx/src/transaction/validity/error.rs
  fuel-vm/Cargo.toml
  fuel-vm/src/backtrace.rs
  fuel-vm/src/storage/blob_data.rs
  fuel-vm/src/storage/contracts_state.rs
Labels: no changelog
