Repository FuelLabs/fuel-vm, pull requests merged in 2024-06, with the labels that each got.

#737 Panic on instructions with non-zero reserved part
  CHANGELOG.md
  fuel-asm/src/lib.rs
  fuel-asm/src/macros.rs
  fuel-vm/Cargo.toml
  fuel-vm/benches/execution.rs
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/interpreter/executors/predicate.rs
  fuel-vm/src/interpreter/initialization.rs
  fuel-vm/src/lib.rs
Labels: breaking, fuel-vm, fuel-asm

#743 Zero $flag on call
  CHANGELOG.md
  fuel-vm/src/interpreter/flow.rs
  fuel-vm/src/tests/flow.rs
Labels: breaking, fuel-vm

#750 Generate and publish code coverage reports in the CI
  .github/workflows/ci.yml
  .github/workflows/scripts/generate_pages_index.py
Labels: no changelog

#753 Fix a bug in CCP instruction
  CHANGELOG.md
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/interpreter/blockchain/code_tests.rs
  fuel-vm/src/interpreter/blockchain/croo_tests.rs
  fuel-vm/src/interpreter/blockchain/other_tests.rs
  fuel-vm/src/interpreter/blockchain/test.rs
  fuel-vm/src/interpreter/blockchain/test/srwq.rs
  fuel-vm/src/interpreter/crypto/tests.rs
  fuel-vm/src/interpreter/memory.rs
  fuel-vm/src/interpreter/memory/allocation_tests.rs
  fuel-vm/src/interpreter/memory/tests.rs
  fuel-vm/src/tests/blockchain.rs
Labels: bug, fuel-vm, audit-report

#765 use the correct gas units for wdop and wqop
  CHANGELOG.md
  fuel-vm/src/interpreter/executors/instruction.rs
Labels: breaking

#774 Removed dead code from the codebase
  fuel-asm/src/args.rs
  fuel-tx/src/consts.rs
  fuel-tx/src/transaction/validity.rs
Labels: no changelog

#754 Test ALU opcodes using only the external interface
  fuel-vm/src/interpreter/alu.rs
  fuel-vm/src/interpreter/alu/tests.rs
  fuel-vm/src/tests/alu.rs
Labels: no changelog

#782 Use companies fork of the `publish-crates` action
  .github/workflows/ci.yml
Labels: no changelog

#779 Refactor coin-based contract instruction tests
  fuel-vm/src/interpreter/contract.rs
  fuel-vm/src/interpreter/contract/tests.rs
  fuel-vm/src/tests/coins.rs
  fuel-vm/src/tests/contract.rs
  fuel-vm/src/tests/mod.rs
  fuel-vm/src/tests/outputs.rs
  fuel-vm/src/util.rs
Labels: testing, no changelog
