Repository FuelLabs/fuel-vm, pull requests merged in 2024-05, with the labels that each got.

#728 Add a single stepping example
  fuel-vm/examples/single_step.rs
Labels: documentation, no changelog

#731 Delete duplicate rustfmt.toml
  rustfmt.toml
Labels: no changelog

#729 Deny clippy::arithmetic_side_effects for fuel-merkle
  CHANGELOG.md
  fuel-merkle/src/binary/merkle_tree.rs
  fuel-merkle/src/binary/node.rs
  fuel-merkle/src/binary/root_calculator.rs
  fuel-merkle/src/binary/verify.rs
  fuel-merkle/src/common.rs
  fuel-merkle/src/common/msb.rs
  fuel-merkle/src/common/node.rs
  fuel-merkle/src/common/path.rs
  fuel-merkle/src/common/path_iterator.rs
  fuel-merkle/src/common/position.rs
  fuel-merkle/src/common/position_path.rs
  fuel-merkle/src/common/subtree.rs
  fuel-merkle/src/lib.rs
  fuel-merkle/src/sparse/merkle_tree.rs
  fuel-merkle/src/sparse/merkle_tree/branch.rs
  fuel-merkle/src/sparse/merkle_tree/node.rs
  fuel-merkle/src/sparse/proof.rs
  fuel-merkle/src/tests/binary_verify.rs
  fuel-merkle/src/tests/sparse.rs
  fuel-merkle/test-helpers/src/binary/merkle_tree.rs
Labels: tech-debt, fuel-merkle

#736 Fix ldc opcode in internal contexts
  CHANGELOG.md
  fuel-crypto/src/secp256/backend.rs
  fuel-types/src/bytes.rs
  fuel-types/src/numeric_types.rs
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/interpreter/blockchain/code_tests.rs
  fuel-vm/src/interpreter/flow.rs
  fuel-vm/src/interpreter/flow/tests.rs
  fuel-vm/src/interpreter/internal.rs
  fuel-vm/src/tests/blockchain.rs
Labels: bug, fuel-vm

#741 chore: Remove erroneous comment about placeholder merges
  fuel-merkle/src/sparse/merkle_tree/node.rs
Labels: no changelog
