Repository FuelLabs/fuel-vm, pull requests merged in 2024-04, with the labels that each got.

#697 Store stack and heap separately
  CHANGELOG.md
  fuel-asm/src/panic_reason.rs
  fuel-types/src/array_types.rs
  fuel-vm/examples/external.rs
  fuel-vm/src/backtrace.rs
  fuel-vm/src/constraints.rs
  fuel-vm/src/consts.rs
  fuel-vm/src/interpreter.rs
  fuel-vm/src/interpreter/alu/wideint.rs
  fuel-vm/src/interpreter/balances.rs
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/interpreter/blockchain/code_tests.rs
  fuel-vm/src/interpreter/blockchain/croo_tests.rs
  fuel-vm/src/interpreter/blockchain/other_tests.rs
  fuel-vm/src/interpreter/blockchain/smo_tests.rs
  fuel-vm/src/interpreter/blockchain/test.rs
  fuel-vm/src/interpreter/blockchain/test/scwq.rs
  fuel-vm/src/interpreter/blockchain/test/srwq.rs
  fuel-vm/src/interpreter/blockchain/test/swwq.rs
  fuel-vm/src/interpreter/constructors.rs
  fuel-vm/src/interpreter/contract.rs
  fuel-vm/src/interpreter/contract/tests.rs
  fuel-vm/src/interpreter/crypto.rs
  fuel-vm/src/interpreter/crypto/tests.rs
  fuel-vm/src/interpreter/diff.rs
  fuel-vm/src/interpreter/diff/tests.rs
  fuel-vm/src/interpreter/executors/instruction.rs
  fuel-vm/src/interpreter/executors/predicate.rs
  fuel-vm/src/interpreter/flow.rs
  fuel-vm/src/interpreter/flow/ret_tests.rs
  fuel-vm/src/interpreter/flow/tests.rs
  fuel-vm/src/interpreter/internal.rs
  fuel-vm/src/interpreter/internal/message_tests.rs
  fuel-vm/src/interpreter/internal/tests.rs
  fuel-vm/src/interpreter/log.rs
  fuel-vm/src/interpreter/log/tests.rs
  fuel-vm/src/interpreter/memory.rs
  fuel-vm/src/interpreter/memory/allocation_tests.rs
  fuel-vm/src/interpreter/memory/impl_tests.rs
  fuel-vm/src/interpreter/memory/stack_tests.rs
  fuel-vm/src/interpreter/memory/tests.rs
  fuel-vm/src/interpreter/metadata.rs
  fuel-vm/src/interpreter/metadata/tests.rs
  fuel-vm/src/lib.rs
  fuel-vm/src/predicate.rs
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/log.rs
  fuel-vm/src/tests/memory.rs
  fuel-vm/src/util.rs
Labels: breaking, fuel-vm, fuel-asm

#713 Add PR template
  .github/pull_request_template.md
Labels: no changelog

#707 A new `Upgrade` transaction to perform network upgrades
  CHANGELOG.md
  Cargo.toml
  fuel-tx/Cargo.toml
  fuel-tx/src/builder.rs
  fuel-tx/src/contract.rs
  fuel-tx/src/lib.rs
  fuel-tx/src/test_helper.rs
  fuel-tx/src/tests/bytes.rs
  fuel-tx/src/tests/display.rs
  fuel-tx/src/tests/mod.rs
  fuel-tx/src/tests/offset.rs
  fuel-tx/src/tests/valid_cases/input.rs
  fuel-tx/src/tests/valid_cases/transaction.rs
  fuel-tx/src/tests/valid_cases/transaction/upgrade.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/consensus_parameters.rs
  fuel-tx/src/transaction/consensus_parameters/gas.rs
  fuel-tx/src/transaction/id.rs
  fuel-tx/src/transaction/metadata.rs
  fuel-tx/src/transaction/repr.rs
  fuel-tx/src/transaction/types.rs
  fuel-tx/src/transaction/types/create.rs
  fuel-tx/src/transaction/types/script.rs
  fuel-tx/src/transaction/types/upgrade.rs
  fuel-tx/src/transaction/validity.rs
  fuel-tx/src/transaction/validity/error.rs
  fuel-tx/test-helpers/Cargo.toml
  fuel-vm/src/checked_transaction.rs
  fuel-vm/src/checked_transaction/types.rs
  fuel-vm/src/interpreter.rs
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/encoding.rs
Labels: breaking

#712 Process `Upgrade` transaction inside of the `Interpreter`
  CHANGELOG.md
  fuel-asm/src/panic_reason.rs
  fuel-tx/src/lib.rs
  fuel-tx/src/transaction/types.rs
  fuel-vm/src/interpreter/blockchain/code_tests.rs
  fuel-vm/src/interpreter/blockchain/croo_tests.rs
  fuel-vm/src/interpreter/blockchain/other_tests.rs
  fuel-vm/src/interpreter/blockchain/smo_tests.rs
  fuel-vm/src/interpreter/blockchain/test.rs
  fuel-vm/src/interpreter/blockchain/test/scwq.rs
  fuel-vm/src/interpreter/blockchain/test/srwq.rs
  fuel-vm/src/interpreter/blockchain/test/swwq.rs
  fuel-vm/src/interpreter/contract/tests.rs
  fuel-vm/src/interpreter/diff/storage.rs
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/interpreter/executors/main/tests.rs
  fuel-vm/src/interpreter/flow/tests.rs
  fuel-vm/src/memory_client.rs
  fuel-vm/src/storage/interpreter.rs
  fuel-vm/src/storage/memory.rs
  fuel-vm/src/storage/predicate.rs
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/metadata.rs
  fuel-vm/src/tests/mod.rs
  fuel-vm/src/tests/upgrade.rs
  fuel-vm/src/transactor.rs
Labels: breaking

#720 A new `Upload` transaction to upload the huge bytecode on the chain
  CHANGELOG.md
  fuel-tx/src/builder.rs
  fuel-tx/src/lib.rs
  fuel-tx/src/test_helper.rs
  fuel-tx/src/tests/bytes.rs
  fuel-tx/src/tests/display.rs
  fuel-tx/src/tests/offset.rs
  fuel-tx/src/tests/valid_cases/transaction.rs
  fuel-tx/src/tests/valid_cases/transaction/upload.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/consensus_parameters.rs
  fuel-tx/src/transaction/fee.rs
  fuel-tx/src/transaction/id.rs
  fuel-tx/src/transaction/metadata.rs
  fuel-tx/src/transaction/repr.rs
  fuel-tx/src/transaction/types.rs
  fuel-tx/src/transaction/types/create.rs
  fuel-tx/src/transaction/types/upload.rs
  fuel-tx/src/transaction/validity.rs
  fuel-tx/src/transaction/validity/error.rs
  fuel-vm/src/checked_transaction.rs
  fuel-vm/src/checked_transaction/types.rs
  fuel-vm/src/interpreter.rs
  fuel-vm/src/tests/encoding.rs
Labels: breaking

#715 Process `Upload` transaction inside the `Interpreter`
  CHANGELOG.md
  fuel-asm/src/panic_reason.rs
  fuel-tx/src/test_helper.rs
  fuel-tx/src/tests/bytes.rs
  fuel-tx/src/tests/valid_cases/transaction/upgrade.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/id.rs
  fuel-tx/src/transaction/types/upgrade.rs
  fuel-tx/src/transaction/types/upload.rs
  fuel-vm/src/error.rs
  fuel-vm/src/interpreter/diff/storage.rs
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/interpreter/executors/main/tests.rs
  fuel-vm/src/memory_client.rs
  fuel-vm/src/storage.rs
  fuel-vm/src/storage/interpreter.rs
  fuel-vm/src/storage/memory.rs
  fuel-vm/src/storage/predicate.rs
  fuel-vm/src/tests/encoding.rs
  fuel-vm/src/tests/mod.rs
  fuel-vm/src/tests/upgrade.rs
  fuel-vm/src/tests/upload.rs
  fuel-vm/src/transactor.rs
Labels: breaking

#719 Handle padded_len_* overflows gracefully
  CHANGELOG.md
  fuel-tx/src/test_helper.rs
  fuel-tx/src/tests/bytes.rs
  fuel-tx/src/transaction/types/chargeable_transaction.rs
  fuel-tx/src/transaction/types/input.rs
  fuel-tx/src/transaction/types/script.rs
  fuel-types/src/bytes.rs
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/predicate.rs
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/metadata.rs
  fuel-vm/src/util.rs
Labels: bug, breaking, fuel-vm, fuel-tx
