Repository FuelLabs/fuel-vm, pull requests merged in 2024-09, with the labels that each got.

#816 Simplifying tests for DA compression
  fuel-compression/src/impls.rs
  fuel-compression/src/traits.rs
  fuel-derive/src/compression/compress.rs
  fuel-derive/src/compression/decompress.rs
  fuel-tx/src/tests/da_compression.rs
  fuel-tx/src/transaction/types/chargeable_transaction.rs
  fuel-tx/src/transaction/types/input/coin.rs
  fuel-tx/src/transaction/types/input/message.rs
Labels: no changelog

#817 chore: Add initial CODEOWNERS file
  .github/CODEOWNERS
Labels: no changelog

#670 DA compression for fuel-tx types
  CHANGELOG.md
  Cargo.toml
  README.md
  fuel-asm/Cargo.toml
  fuel-compression/Cargo.toml
  fuel-compression/src/impls.rs
  fuel-compression/src/key.rs
  fuel-compression/src/lib.rs
  fuel-compression/src/traits.rs
  fuel-crypto/src/secp256/signature.rs
  fuel-derive/Cargo.toml
  fuel-derive/README.md
  fuel-derive/src/canonical/attribute.rs
  fuel-derive/src/canonical/deserialize.rs
  fuel-derive/src/canonical/serialize.rs
  fuel-derive/src/compression/attribute.rs
  fuel-derive/src/compression/compress.rs
  fuel-derive/src/compression/decompress.rs
  fuel-derive/src/helpers.rs
  fuel-derive/src/lib.rs
  fuel-tx/Cargo.toml
  fuel-tx/src/builder.rs
  fuel-tx/src/lib.rs
  fuel-tx/src/tests/da_compression.rs
  fuel-tx/src/tests/mod.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/policies.rs
  fuel-tx/src/transaction/types.rs
  fuel-tx/src/transaction/types/blob.rs
  fuel-tx/src/transaction/types/chargeable_transaction.rs
  fuel-tx/src/transaction/types/create.rs
  fuel-tx/src/transaction/types/input.rs
  fuel-tx/src/transaction/types/input/coin.rs
  fuel-tx/src/transaction/types/input/contract.rs
  fuel-tx/src/transaction/types/input/message.rs
  fuel-tx/src/transaction/types/input/predicate.rs
  fuel-tx/src/transaction/types/input/snapshot_tests.rs
  fuel-tx/src/transaction/types/mint.rs
  fuel-tx/src/transaction/types/output.rs
  fuel-tx/src/transaction/types/output/contract.rs
  fuel-tx/src/transaction/types/script.rs
  fuel-tx/src/transaction/types/storage.rs
  fuel-tx/src/transaction/types/upgrade.rs
  fuel-tx/src/transaction/types/upload.rs
  fuel-tx/src/transaction/types/utxo_id.rs
  fuel-tx/src/transaction/types/witness.rs
  fuel-tx/src/transaction/validity.rs
  fuel-tx/src/tx_pointer.rs
  fuel-types/src/array_types.rs
  fuel-types/src/tests/types.rs
  fuel-vm/Cargo.toml
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/lib.rs
Labels: fuel-types, mainnet

#829 Add `fn add_fee_input()` and make `fn add_random_fee_input()` truly random
  fuel-tx/src/builder.rs
  fuel-tx/src/tests/valid_cases/transaction.rs
  fuel-tx/src/tests/valid_cases/transaction/blob.rs
  fuel-tx/src/tests/valid_cases/transaction/upgrade.rs
  fuel-tx/src/tests/valid_cases/transaction/upload.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/types/create.rs
  fuel-vm/benches/execution.rs
  fuel-vm/examples/external.rs
  fuel-vm/examples/single_step.rs
  fuel-vm/src/interpreter/debug.rs
  fuel-vm/src/interpreter/executors/instruction/tests/reserved_registers.rs
  fuel-vm/src/interpreter/executors/main/tests.rs
  fuel-vm/src/interpreter/internal/tests.rs
  fuel-vm/src/interpreter/memory/tests.rs
  fuel-vm/src/predicate.rs
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/crypto.rs
  fuel-vm/src/tests/external.rs
  fuel-vm/src/tests/memory.rs
  fuel-vm/src/tests/metadata.rs
  fuel-vm/src/util.rs
Labels: no changelog

#833 Add `Display` and `Error` impls to custom error type `SettingBlockTransactionSizeLimitNotSupported`
  fuel-tx/src/transaction/consensus_parameters.rs
Labels: no changelog

#835 Fixing WASM-NPM packaging and publishing
  .github/workflows/ci.yml
  .npm/.scripts/prepare-wasm-packages.sh
  .npm/package.json
  .npm/packages/fuel-asm/index.test.mjs
  .npm/packages/fuel-tx/index.test.mjs
  .npm/packages/fuel-types/index.test.mjs
  .npm/pnpm-lock.yaml
  .npm/turbo.json
  CHANGELOG.md
Labels: bug
