Repository FuelLabs/fuel-vm, pull requests merged in 2024-10, with the labels that each got.

#845 fix(SecretKey): remove Default implementation
  CHANGELOG.md
  fuel-crypto/src/secp256/secret.rs
Labels: breaking

#844 WDCM and WQCM: reset $of and $err
  CHANGELOG.md
  fuel-vm/src/interpreter/alu/wideint.rs
  fuel-vm/src/tests/wideint.rs
Labels: breaking, fuel-vm

#766 Correct the price to verify native signatures
  CHANGELOG.md
  fuel-tx/src/transaction/fee.rs
  fuel-vm/src/checked_transaction.rs
Labels: breaking

#851 Update CODEOWNERS
  .github/CODEOWNERS
Labels: no changelog

#854 Fix incorrect padding of LDC mode 2 and release 0.58.2
  CHANGELOG.md
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/tests/blockchain/ldc_mode_2.rs
Labels: bug, fuel-vm

#855 Release v0.58.2
  Cargo.toml
Labels: no changelog

#858 Create SECURITY.md
  SECURITY.md
Labels: no changelog
