Repository FuelLabs/fuel-vm, pull requests merged in 2024-07, with the labels that each got.

#788 grow_stack and empty $hp range write fixes
  CHANGELOG.md
  fuel-vm/src/interpreter/memory.rs
  fuel-vm/src/interpreter/memory/tests.rs
Labels: bug

#780 Blob tx and instructions
  CHANGELOG.md
  fuel-asm/src/lib.rs
  fuel-asm/src/panic_reason.rs
  fuel-tx/src/builder.rs
  fuel-tx/src/lib.rs
  fuel-tx/src/test_helper.rs
  fuel-tx/src/tests/offset.rs
  fuel-tx/src/tests/valid_cases/transaction.rs
  fuel-tx/src/tests/valid_cases/transaction/blob.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/consensus_parameters.rs
  fuel-tx/src/transaction/consensus_parameters/gas.rs
  fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
  fuel-tx/src/transaction/id.rs
  fuel-tx/src/transaction/metadata.rs
  fuel-tx/src/transaction/repr.rs
  fuel-tx/src/transaction/types.rs
  fuel-tx/src/transaction/types/blob.rs
  fuel-tx/src/transaction/validity.rs
  fuel-tx/src/transaction/validity/error.rs
  fuel-types/src/array_types.rs
  fuel-vm/src/checked_transaction.rs
  fuel-vm/src/checked_transaction/types.rs
  fuel-vm/src/interpreter.rs
  fuel-vm/src/interpreter/blob.rs
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/interpreter/diff/storage.rs
  fuel-vm/src/interpreter/executors/instruction.rs
  fuel-vm/src/interpreter/executors/instruction/tests/reserved_registers.rs
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/interpreter/gas.rs
  fuel-vm/src/interpreter/initialization.rs
  fuel-vm/src/interpreter/memory.rs
  fuel-vm/src/interpreter/memory/tests.rs
  fuel-vm/src/lib.rs
  fuel-vm/src/memory_client.rs
  fuel-vm/src/storage.rs
  fuel-vm/src/storage/blob_data.rs
  fuel-vm/src/storage/interpreter.rs
  fuel-vm/src/storage/memory.rs
  fuel-vm/src/storage/predicate.rs
  fuel-vm/src/tests/alu.rs
  fuel-vm/src/tests/blob.rs
  fuel-vm/src/tests/blockchain.rs
  fuel-vm/src/tests/coins.rs
  fuel-vm/src/tests/encoding.rs
  fuel-vm/src/tests/mod.rs
  fuel-vm/src/tests/test_helpers.rs
  fuel-vm/src/transactor.rs
  fuel-vm/src/util.rs
Labels: breaking, fuel-vm, fuel-asm, fuel-tx

#795 Change `ed19` to work with arbitrary-length messages
  CHANGELOG.md
  fuel-asm/src/lib.rs
  fuel-crypto/src/ed25519.rs
  fuel-tx/src/transaction/consensus_parameters/gas.rs
  fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
  fuel-vm/src/interpreter/crypto.rs
  fuel-vm/src/interpreter/crypto/tests.rs
  fuel-vm/src/interpreter/executors/instruction.rs
  fuel-vm/src/tests/crypto.rs
Labels: breaking
