Repository FuelLabs/fuel-vm, pull requests merged in 2024-03, with the labels that each got.

#692 Add GTF getters for tx bytes size and address
  CHANGELOG.md
  fuel-asm/src/args.rs
  fuel-vm/src/interpreter/metadata.rs
  fuel-vm/src/interpreter/metadata/tests.rs
  fuel-vm/src/tests/metadata.rs
Labels: breaking, fuel-asm

#696 dev: refactor smt node visibility
  fuel-merkle/src/common.rs
  fuel-merkle/src/common/hash.rs
  fuel-merkle/src/sparse.rs
  fuel-merkle/src/sparse/hash.rs
  fuel-merkle/src/sparse/in_memory.rs
  fuel-merkle/src/sparse/merkle_tree.rs
  fuel-merkle/src/sparse/merkle_tree/branch.rs
  fuel-merkle/src/sparse/merkle_tree/node.rs
  fuel-merkle/src/sparse/primitive.rs
  fuel-merkle/src/sparse/proof.rs
  fuel-merkle/src/tests/sparse.rs
Labels: no changelog

#698 Increase size of inputs, outputs and witnesses to uint16
  .npm/packages/fuel-tx/index.test.cjs
  .npm/packages/fuel-tx/index.test.mjs
  CHANGELOG.md
  fuel-tx/src/builder.rs
  fuel-tx/src/tests/valid_cases/input.rs
  fuel-tx/src/tests/valid_cases/output.rs
  fuel-tx/src/transaction.rs
  fuel-tx/src/transaction/consensus_parameters.rs
  fuel-tx/src/transaction/fee.rs
  fuel-tx/src/transaction/id.rs
  fuel-tx/src/transaction/types/create.rs
  fuel-tx/src/transaction/types/input.rs
  fuel-tx/src/transaction/types/input/coin.rs
  fuel-tx/src/transaction/types/input/message.rs
  fuel-tx/src/transaction/types/output.rs
  fuel-tx/src/transaction/types/output/contract.rs
  fuel-tx/src/transaction/types/utxo_id.rs
  fuel-tx/src/transaction/validity.rs
  fuel-vm/src/checked_transaction.rs
  fuel-vm/src/interpreter.rs
  fuel-vm/src/tests/limits.rs
  fuel-vm/src/tests/mod.rs
  fuel-vm/src/util.rs
Labels: breaking, fuel-vm, fuel-tx

#704 feat: `serde::Serialize` and `serde::Deserialize` for `double_key!`
  fuel-vm/Cargo.toml
  fuel-vm/src/storage.rs
Labels: enhancement, no changelog

#710 Missed functionality required to for upgrading `fuel-core` to next `fuel-vm` release
  fuel-tx/src/lib.rs
  fuel-tx/src/transaction/consensus_parameters/gas.rs
  fuel-tx/src/transaction/types/utxo_id.rs
Labels: no changelog
