Repository FuelLabs/fuel-vm, pull requests merged in 2025-02, with the labels that each got.

#907 Remove unnecessary return values from Storage{Read, Write} methods
  CHANGELOG.md
  fuel-storage/src/impls.rs
  fuel-storage/src/lib.rs
  fuel-vm/src/interpreter/diff/storage.rs
  fuel-vm/src/interpreter/flow.rs
  fuel-vm/src/interpreter/memory.rs
  fuel-vm/src/storage/interpreter.rs
  fuel-vm/src/storage/memory.rs
  fuel-vm/src/storage/predicate.rs
Labels: breaking, tech-debt, fuel-storage

#908 Bugfix: more receipt generation issues with debugger
  CHANGELOG.md
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/interpreter/internal.rs
  fuel-vm/src/interpreter/internal/message_tests.rs
  fuel-vm/src/tests/debugger.rs
Labels: bug

#916 chore: allow releases to NPM
  .github/workflows/ci.yml
Labels: no changelog

#883 use Vec::with_capacity avoid realloc
  fuel-merkle/src/binary/merkle_tree.rs
  fuel-tx/src/transaction/metadata.rs
Labels: no changelog, cla:signed

#918 continue-on-error foundations: refactor verification to a separate trait
  CHANGELOG.md
  fuel-vm/examples/external.rs
  fuel-vm/src/backtrace.rs
  fuel-vm/src/interpreter.rs
  fuel-vm/src/interpreter/alu.rs
  fuel-vm/src/interpreter/alu/muldiv.rs
  fuel-vm/src/interpreter/alu/wideint.rs
  fuel-vm/src/interpreter/balances.rs
  fuel-vm/src/interpreter/blob.rs
  fuel-vm/src/interpreter/blockchain.rs
  fuel-vm/src/interpreter/blockchain/code_tests.rs
  fuel-vm/src/interpreter/blockchain/croo_tests.rs
  fuel-vm/src/interpreter/blockchain/other_tests.rs
  fuel-vm/src/interpreter/constructors.rs
  fuel-vm/src/interpreter/contract.rs
  fuel-vm/src/interpreter/crypto.rs
  fuel-vm/src/interpreter/debug.rs
  fuel-vm/src/interpreter/diff.rs
  fuel-vm/src/interpreter/diff/storage.rs
  fuel-vm/src/interpreter/ecal.rs
  fuel-vm/src/interpreter/executors/debug.rs
  fuel-vm/src/interpreter/executors/instruction.rs
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/interpreter/executors/opcodes_impl.rs
  fuel-vm/src/interpreter/flow.rs
  fuel-vm/src/interpreter/flow/tests.rs
  fuel-vm/src/interpreter/gas.rs
  fuel-vm/src/interpreter/initialization.rs
  fuel-vm/src/interpreter/internal.rs
  fuel-vm/src/interpreter/log.rs
  fuel-vm/src/interpreter/memory.rs
  fuel-vm/src/interpreter/metadata.rs
  fuel-vm/src/interpreter/post_execution.rs
  fuel-vm/src/lib.rs
  fuel-vm/src/memory_client.rs
  fuel-vm/src/storage/memory.rs
  fuel-vm/src/tests/external.rs
  fuel-vm/src/transactor.rs
  fuel-vm/src/util.rs
  fuel-vm/src/verification.rs
Labels: breaking, fuel-vm

#919 Pin base64ct to non-MSRV-breaking version
  fuel-crypto/Cargo.toml
  fuel-crypto/src/lib.rs
Labels: no changelog

#915 Dry run mode: continue-on-error handling for "contract not in inputs"
  CHANGELOG.md
  fuel-vm/src/tests/continue_on_error.rs
  fuel-vm/src/tests/mod.rs
  fuel-vm/src/util.rs
  fuel-vm/src/verification.rs
Labels: enhancement, fuel-vm
