Repository FuelLabs/fuel-vm, pull requests merged in 2025-01, with the labels that each got.

#889 bugfix: Produce correct receipts with debugger breakpoints enabled
  CHANGELOG.md
  fuel-vm/src/interpreter/executors/main.rs
  fuel-vm/src/tests/crypto.rs
  fuel-vm/src/tests/debugger.rs
  fuel-vm/src/tests/mod.rs
Labels: bug, fuel-vm

#898 Better usage of STD features in our dependencies
  fuel-crypto/Cargo.toml
  fuel-crypto/src/secp256/backend/k1/secp256k1.rs
  fuel-crypto/src/secp256/signature_format.rs
  fuel-vm/Cargo.toml
Labels: no changelog, xxx

#903 fix: deprecation message
  .npm/.scripts/template/src/index.js
  CHANGELOG.md
Labels: bug

#900 Compare nonce instead of message id of inputs to catch duplicates
  CHANGELOG.md
  fuel-tx/src/tests/valid_cases/input.rs
  fuel-tx/src/transaction/validity.rs
  fuel-tx/src/transaction/validity/error.rs
Labels: breaking

#896 Expose `leaf_sum` and allow binary `MerkleTree` to be built from existing precomputed leafs
  CHANGELOG.md
  fuel-merkle/src/binary.rs
  fuel-merkle/src/binary/node.rs
  fuel-merkle/src/binary/root_calculator.rs
Labels: xxx
